@ECHO OFF
SETLOCAL

SET PROG_ZANDRONUM="%DOOMDIR%\Zandronum\zandronum.EXE"
SET ZANFLAGSVALUE=""

IF DEFINED ZANFLAGS (
    SET ZANFLAGS_VALUE=%ZANFLAGS%
)

CALL %PROG_ZANDRONUM% -file "%CD%/PK3 Source" -file "%CD%/PK3_Source_Zandronum" -host %ZANFLAGS_VALUE% %*