/*
**  Se7evidas - A GZDoom mod
**  Copyright (C) 2015-???  Chronos Ouroboros
**
**  This program is free software; you can redistribute it and/or modify
**  it under the terms of the GNU General Public License as published by
**  the Free Software Foundation; either version 2 of the License, or
**  (at your option) any later version.
**
**  This program is distributed in the hope that it will be useful,
**  but WITHOUT ANY WARRANTY; without even the implied warranty of
**  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
**  GNU General Public License for more details.
**
**  You should have received a copy of the GNU General Public License along
**  with this program; if not, write to the Free Software Foundation, Inc.,
**  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/

#include "includes.h"
#include "misc/names.h"

string NL_Eng_Fore [] = {
    s"Aaron",
    s"Adam",
    s"Adrian",
    s"Alex",
    s"Andrew",
    s"Anthony",
    s"Ben",
    s"Bob",
    s"Brian",
    s"Chris",
    s"Christoph",
    s"Christopher",
    s"Clark",
    s"Colin",
    s"Corey",
    s"Daniel",
    s"Dave",
    s"David",
    s"Dominic",
    s"Drake",
    s"Duncan",
    s"Edward",
    s"Evan",
    s"Felix",
    s"Frank",
    s"Franklin",
    s"Gordon",
    s"Greg",
    s"Gregor",
    s"Gregory",
    s"Holt",
    s"Jack",
    s"James",
    s"Jamie",
    s"Jay",
    s"Jerry",
    s"Jim",
    s"John",
    s"Jonathan",
    s"Josh",
    s"Joshua",
    s"Ken",
    s"Kenneth",
    s"Kevin",
    s"Malcolm",
    s"Marcus",
    s"Mark",
    s"Markus",
    s"Matt",
    s"Matthew",
    s"Max",
    s"Maxwell",
    s"Michael",
    s"Morgan",
    s"Nicholas",
    s"Nick",
    s"Odysseus",
    s"Owen",
    s"Patrick",
    s"Paul",
    s"Perry",
    s"Pete",
    s"Peter",
    s"Phil",
    s"Philip",
    s"Richard",
    s"Rob",
    s"Robert",
    s"Roger",
    s"Ryan",
    s"Sam",
    s"Samuel",
    s"Scott",
    s"Sean",
    s"Shane",
    s"Shawn",
    s"Simon",
    s"Stephen",
    s"Steve",
    s"Steven",
    s"Taylor",
    s"Thomas",
    s"Tim",
    s"Timothy",
    s"Tom",
    s"Trent",
    s"Warren",
};
int NL_Eng_Fore_Length = sizeof (NL_Eng_Fore);

string NL_Eng_Sur [] = {
    s"Blake",
    s"Blossom",
    s"Burton",
    s"Cage",
    s"Carmack",
    s"Carter",
    s"Caruso",
    s"Castle",
    s"Cawthon",
    s"Christopherson",
    s"Clarke",
    s"Cloud",
    s"Connor",
    s"Constantine",
    s"Davis",
    s"Dawson",
    s"Evans",
    s"Fisk",
    s"Foster",
    s"Freeman",
    s"Fuchs",
    s"Grayson",
    s"Green",
    s"Grimm",
    s"Hamilton",
    s"Harrell",
    s"Harris",
    s"Harty",
    s"Hawkins",
    s"Hayter",
    s"Holmes",
    s"Horner",
    s"House",
    s"Jackson",
    s"Johnson",
    s"Jones",
    s"Jovanovic",
    s"Kent",
    s"Lee",
    s"Lewis",
    s"Locke",
    s"Lubin",
    s"Lynch",
    s"MacArthur",
    s"Martin",
    s"McGee",
    s"Miller",
    s"Mills",
    s"Moore",
    s"Navarro",
    s"Perotta",
    s"Petersen",
    s"Pike",
    s"Porter",
    s"Pratchett",
    s"Prince",
    s"Punchatz",
    s"Reynolds",
    s"Reznor",
    s"Rhinehart",
    s"Rock",
    s"Romero",
    s"Schilder",
    s"Singer",
    s"Stewart",
    s"Taylor",
    s"Townshend",
    s"Voorhees",
    s"Walsh",
    s"Waters",
    s"Watson",
    s"Whitten",
    s"Wilbur",
    s"Willits",
    s"Wyman",
    s"Young",
};
int NL_Eng_Sur_Length = sizeof (NL_Eng_Sur);