//-------------------------------------------------------------------------------------------
//
// Misc
//
//-------------------------------------------------------------------------------------------
class S7_UpgradeRadar : S7_Boolean { }
class S7_UpgradeRegen : S7_Boolean { }
class S7_UpgradeRegenPower : S7_Counter { default { Inventory.MaxAmount 2; } }
class S7_UpgradeSlot1 : S7_Boolean { }
class S7_UpgradeSlot2 : S7_Boolean { }
class S7_UpgradeSlot3 : S7_Boolean { }
class S7_UpgradeSlot4 : S7_Boolean { }
class S7_UpgradeSlot5 : S7_Boolean { }