#INCLUDE "zcommon.acs"
#LIBRARY "Se7evidas"

// Defines
#DEFINE MAXPLAYERS 64

// Includes
#INCLUDE "commonFuncs.h"
#INCLUDE "Weapon Stuff.ACS"
#INCLUDE "Health.ACS"
#INCLUDE "Stamina.ACS"
#INCLUDE "Sprint System.ACS"
#INCLUDE "Misc.ACS"

// Defines

// Highest script num ID: 908

script 906 ENTER {
	setActorProperty (0, APROP_SPEED, 1.0);
	S7_SR_StaminaEmpty [playerNumber ()] = 0;
}

script 907 RESPAWN {
	setActorProperty (0, APROP_SPEED, 1.0);
	S7_SR_StaminaEmpty [playerNumber ()] = 0;
}